"""Shared data contracts for the loop + memory architecture."""

from .models import (
    CodeContext,
    CodeSnippet,
    EpisodeCandidate,
    FileCandidate,
    FileRole,
    LocalizerResult,
    MemoryLayer,
    PatchChange,
    PatchResult,
    PlanStep,
    PlannerInput,
    PolicyDocument,
    Priority,
    RetryDecision,
    ReviewFeedback,
    ReviewIssue,
    StructuredPlan,
    TaskContext,
    TaskEvent,
    TaskContextRef,
    UserRequest,
)

__all__ = [
    "CodeContext",
    "CodeSnippet",
    "EpisodeCandidate",
    "FileCandidate",
    "FileRole",
    "LocalizerResult",
    "MemoryLayer",
    "PatchChange",
    "PatchResult",
    "PlanStep",
    "PlannerInput",
    "PolicyDocument",
    "Priority",
    "RetryDecision",
    "ReviewFeedback",
    "ReviewIssue",
    "StructuredPlan",
    "TaskContext",
    "TaskEvent",
    "TaskContextRef",
    "UserRequest",
]
