from typing import Protocol

from forge.domain.memory import L0Event, L0SessionManifest


class L0EventStore(Protocol):
    def create_session(self, manifest: L0SessionManifest) -> None: ...
    def get_manifest(self, session_id: str) -> L0SessionManifest: ...
    def append(self, event: L0Event) -> L0Event: ...
    def list_events(self, session_id: str) -> tuple[L0Event, ...]: ...
    def mark_completed(self, session_id: str) -> None: ...
