from typing import Protocol

from forge.domain.procedural import ProceduralSkill, SkillExecution


class ProceduralRepository(Protocol):
    def get(self, skill_id: str) -> ProceduralSkill | None: ...
    def get_by_source_l2(self, knowledge_id: str) -> ProceduralSkill | None: ...
    def list_active(self) -> list[ProceduralSkill]: ...
    def upsert(self, skill: ProceduralSkill) -> None: ...
    def record_execution(self, execution: SkillExecution) -> None: ...
    def executions_for(self, skill_id: str) -> list[SkillExecution]: ...
